---
- hosts: all
  sudo: yes
  tasks:
  - name: Add Juju
    apt_repository:
      repo: 'ppa:juju/stable'
  - name: Install Juju
    apt:
      name: "{{ item }}"
      cache_valid_time: 3600
    with_items:
      - juju-quickstart
      - juju-local
