---
- hosts: all
  gather_facts: no
  sudo: yes
  vars:
    user:
      name: ntangsurat
      uid: 3461
  tasks:
    - name: Install essentials
      apt: update_cache=yes cache_valid_time=3600 name={{ item }}
      with_items:
        - firefox
        - vim
        - tmux
        - icedtea-plugin
        - xterm
        - gnome-terminal
    - name: Add user
      user: name={{ user.name }}
            uid={{ user.uid }}
            groups=sudo
            shell=/bin/bash
    - name: Passwordless sudo
      template: dest=/etc/sudoers.d/{{ user.name }}-sudo
                src=user-sudo.j2
                validate='visudo -cf %s'
    - name: Add authorized_key
      authorized_key: user={{ user.name }}
                      key="{{ item }}"
      with_file:
        - ~/.ssh/id_dsa.pub
